name: Go

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Run
      run: ./twitclean 
      env: 
        TC_TWITTER_ACCESS_TOKEN: ${{ secrets.TC_TWITTER_ACCESS_TOKEN }}
        TC_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TC_TWITTER_ACCESS_TOKEN_SECRET }}
        TC_TWITTER_CONSUMER_KEY: ${{ secrets.TC_TWITTER_CONSUMER_KEY }}
        TC_TWITTER_CONSUMER_SECRET: ${{ secrets.TC_TWITTER_CONSUMER_SECRET }}
